Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>>     1 #! /usr/bin/env python
    2 #  -*- coding: utf-8 -*-
    3 #
    4 # GUI module generated by PAGE version 6.2
    5 #  in conjunction with Tcl version 8.6
    6 #    Feb 19, 2022 07:34:54 PM EET  platform: Windows NT
    7 
    8 import sys
    9 
   10 try:
   11     import Tkinter as tk
   12 except ImportError:
   13     import tkinter as tk
   14 
   15 try:
   16     import ttk
   17     py3 = False
   18 except ImportError:
   19     import tkinter.ttk as ttk
   20     py3 = True
   21 
   22 import githubok_support
   23 
   24 def vp_start_gui():
   25     '''Starting point when module is the main routine.'''
   26     global val, w, root
   27     root = tk.Tk()
   28     top = Toplevel1 (root)
   29     githubok_support.init(root, top)
   30     root.mainloop()
   31 
   32 w = None
   33 def create_Toplevel1(rt, *args, **kwargs):
   34     '''Starting point when module is imported by another module.
   35        Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
   36     global w, w_win, root
   37     #rt = root
   38     root = rt
   39     w = tk.Toplevel (root)
   40     top = Toplevel1 (w)
   41     githubok_support.init(w, top, *args, **kwargs)
   42     return (w, top)
   43 
   44 def destroy_Toplevel1():
   45     global w
   46     w.destroy()
   47     w = None
   48 
   49 class Toplevel1:
   50     def __init__(self, top=None):
   51         '''This class configures and populates the toplevel window.
   52            top is the toplevel containing window.'''
   53         _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
   54         _fgcolor = '#000000'  # X11 color: 'black'
   55         _compcolor = '#d9d9d9' # X11 color: 'gray85'
   56         _ana1color = '#d9d9d9' # X11 color: 'gray85'
   57         _ana2color = '#ececec' # Closest X11 color: 'gray92'
   58 
   59         top.geometry("600x450+383+106")
   60         top.minsize(116, 1)
   61         top.maxsize(1366, 746)
   62         top.resizable(1,  1)
   63         top.title("New Toplevel")
   64         top.configure(background="#d9d9d9")
   65 
   66         self.Canvas1 = tk.Canvas(top)
   67         self.Canvas1.place(relx=0.183, rely=0.089, relheight=0.518
   68                 , relwidth=0.572)
   69         self.Canvas1.configure(background="#d9d9d9")
   70         self.Canvas1.configure(borderwidth="2")
   71         self.Canvas1.configure(insertbackground="black")
   72         self.Canvas1.configure(relief="ridge")
   73         self.Canvas1.configure(selectbackground="blue")
   74         self.Canvas1.configure(selectforeground="white")
   75 
   76         self.Button1 = tk.Button(top)
   77         self.Button1.place(relx=0.417, rely=0.667, height=24, width=46)
   78         self.Button1.configure(activebackground="#ececec")
   79         self.Button1.configure(activeforeground="#000000")
   80         self.Button1.configure(background="#d9d9d9")
   81         self.Button1.configure(command=githubok_support.github.com)
   82         self.Button1.configure(disabledforeground="#a3a3a3")
   83         self.Button1.configure(foreground="#000000")
   84         self.Button1.configure(highlightbackground="#d9d9d9")
   85         self.Button1.configure(highlightcolor="black")
   86         self.Button1.configure(pady="0")
   87         self.Button1.configure(text='''Button''')
   88 
   89         self.Button2 = tk.Button(top)
   90         self.Button2.place(relx=0.417, rely=0.778, height=24, width=46)
   91         self.Button2.configure(activebackground="#ececec")
   92         self.Button2.configure(activeforeground="#000000")
   93         self.Button2.configure(background="#d9d9d9")
   94         self.Button2.configure(command=githubok_support.Close)
   95         self.Button2.configure(disabledforeground="#a3a3a3")
   96         self.Button2.configure(foreground="#000000")
   97         self.Button2.configure(highlightbackground="#d9d9d9")
   98         self.Button2.configure(highlightcolor="black")
   99         self.Button2.configure(pady="0")
  100         self.Button2.configure(text='''Button''')
  101 
  102 if __name__ == '__main__':
  103     vp_start_gui()
  104 
  105 

